---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-{{.Values.app.name}}
  namespace: {{.Values.app.namespace}}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
  nfs:
    server: {{.Values.app.efs_dns}}
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-{{.Values.app.name}}
  namespace: {{.Values.app.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: efs-pv-{{.Values.app.name}}
